services:
  seanime:
    image: ghcr.io/cat-ling/seanime:latest
    container_name: seanime
    restart: unless-stopped
    volumes:
      - seanime_data:/data
    expose:
      - "43211"
    environment:
      - SEANIME_DATA_DIR=/data
      - SEANIME_SERVER_HOST=0.0.0.0
      - SEANIME_SERVER_PORT=43211
      - SEANIME_WORKING_DIR=/app
    networks:
      - nginx

volumes:
  seanime_data:

networks:
  nginx:
    external: true
